version: '3'
services:
  caly-app-backend:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

volumes:
  redis-data:
