name: Update VPS
on:
  push:
    branches:
      - master

jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Deploy using Docker Compose
        run:
          docker-compose up -d
        env:
          DOCKER_BUILDKIT: 1
