name: Update VPS
on:
  push:
    branches:
      - master

jobs:
  update_vps:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2


      - name: Build and Deploy Caly using Docker Compose
        run: |
          docker-compose pull
          docker-compose up --build --force-recreate --no-deps -d
        env:
          DOCKER_BUILDKIT: 1
